# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 601dbd015f1ac03237aaade00b7eb2a7fdff62709f10288a75e78bc673fa3ae15a63168bb97f9cc0b2a68259205a3175b93035174358622e3e5324655e46e7cc

test:
  secret_key_base: c61b863a6bebcec42cee0ea1521c3d7ce7d942fdb3967b2216077f89486f372457d83e02ae0c9e2cdc043e4c29dd9691597fd2ab1fe04cbee0fbf5dda306e983

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
